import type { ChapterStepProps } from "../../registry/types";
import "./CmdManage.css";

const Cmd=({children}:{children:React.ReactNode})=><div className="cm-cmd">$ {children}</div>;
const Folder=({label,className=""}:{label:string;className?:string})=><div className={`cm-folder card ${className}`}><b>{label}</b><div><i/><i/><i/></div></div>;

export default function CmdManage({step}:ChapterStepProps){
 if(step===0)return <div className="cm-scene cm-index scene-pad"><h1>用完要收。</h1><p>五種維護動作，一個一個看。</p><div className="cm-wheel">{["remove","move","repair","prune","lock"].map((x,i)=><div key={x} style={{transform:`rotate(${i*72}deg) translateY(-250px) rotate(${-i*72}deg)`,animationDelay:`${i*100}ms`}}>{x}</div>)}<b>worktree</b></div></div>;
 if(step===1)return <div className="cm-scene cm-remove scene-pad"><p>01 · REMOVE</p><h1>先確認<span>變更已保存。</span></h1><Cmd>git worktree remove ../project-hotfix</Cmd><div className="cm-remove-demo"><Folder label="project-hotfix/"/><div className="cm-gate"><strong>REFUSED</strong><span>modified files<br/>untracked files</span><i/></div><div className="cm-clean"><b>CLEAN</b><span>commit or stash first</span></div></div></div>;
 if(step===2)return <div className="cm-scene cm-branch scene-pad"><p>02 · TWO SEPARATE ACTIONS</p><h1>移除 worktree<br/><span>不等於刪 branch。</span></h1><div className="cm-two-actions"><div><Folder label="../project-hotfix" className="cm-fade-folder"/><Cmd>git worktree remove</Cmd><strong>WORKTREE　GONE</strong></div><div className="cm-not-equal">≠</div><div><div className="cm-branch-line"><i/><b>hotfix/payment-timeout</b></div><Cmd>git branch -d</Cmd><strong>MERGED FIRST</strong></div></div></div>;
 if(step===3)return <div className="cm-scene cm-move scene-pad"><p>03 · MOVE</p><h1>搬位置，<span>讓 Git 一起搬。</span></h1><Cmd>git worktree move ../project-hotfix ../worktrees/hotfix</Cmd><div className="cm-move-demo"><Folder label="../project-hotfix"/><div className="cm-route"><i>→</i><span>metadata updated</span></div><Folder label="../worktrees/hotfix"/></div><div className="cm-no-drag">不要直接拖曳資料夾</div></div>;
 if(step===4)return <div className="cm-scene cm-repair scene-pad"><p>04 · REPAIR</p><h1>關聯斷了，<span>接回來。</span></h1><Cmd>git worktree repair ../moved-hotfix</Cmd><div className="cm-repair-demo"><div className="cm-admin card"><b>$GIT_DIR/worktrees/</b><i/></div><svg viewBox="0 0 800 300"><path pathLength="1" d="M20 150 H315 M485 150 H780"/><path className="cm-mend" d="M315 150 Q400 40 485 150"/></svg><Folder label="../moved-hotfix"/></div></div>;
 if(step===5)return <div className="cm-scene cm-prune scene-pad"><p>05 · PRUNE</p><h1>資料夾不在了，<br/><span>清過期管理資訊。</span></h1><Cmd>git worktree prune</Cmd><div className="cm-prune-demo">{["active/main","active/feature","stale/hotfix","stale/release"].map((x,i)=><div className={i>1?"cm-stale":""} key={x}><i/><b>{x}</b><span>{i>1?"missing directory":"valid"}</span></div>)}</div><div className="cm-sweep"/></div>;
 if(step===6)return <div className="cm-scene cm-lock scene-pad"><p>06 · LOCK</p><h1>偶爾離線？<span>先鎖住。</span></h1><Cmd>git worktree lock --reason "USB drive" ../portable</Cmd><div className="cm-lock-demo"><Folder label="../portable"/><div className="cm-padlock"><div/><b>LOCKED</b><span>reason: USB drive</span></div><div className="cm-prune-wave">PRUNE →</div></div><small>隨身碟 · 離線網路磁碟 · 可卸除裝置</small></div>;
 return null;
}
