import type { ChapterStepProps } from "../../registry/types";
import "./Traps.css";

const Tree=({name,branch}:{name:string;branch:string})=><div className="tp-tree card"><b>{name}</b><span>{branch}</span><div><i/><i/><i/></div></div>;

export default function Traps({step}:ChapterStepProps){
 if(step===0)return <div className="tp-scene tp-intro scene-pad"><div className="tp-hole"><i/><i/><i/></div><h1>開始用之前，<br/><span>先看見這些坑。</span></h1><div className="tp-sign">SHARED ≠ ISOLATED</div></div>;
 if(step===1)return <div className="tp-scene tp-same scene-pad"><p>TRAP 01</p><h1>同一個 local branch，<br/><span>不能同時 checkout 兩次。</span></h1><div className="tp-same-demo"><Tree name="worktree A" branch="feature/login"/><div className="tp-block"><b>BLOCKED</b><i/></div><Tree name="worktree B" branch="feature/login"/></div><div className="tp-message">fatal: 'feature/login' is already checked out</div></div>;
 if(step===2)return <div className="tp-scene tp-ref scene-pad"><p>WHY GIT STOPS YOU</p><h1>避免兩邊同時推進<br/><span>同一個 ref。</span></h1><div className="tp-ref-demo"><div className="tp-worker">A<i>commit</i></div><div className="tp-worker">B<i>commit</i></div><svg viewBox="0 0 1100 430"><path pathLength="1" d="M150 80 C250 80 320 210 470 210 H930"/><path pathLength="1" d="M150 350 C250 350 320 210 470 210"/></svg><div className="tp-ref-line"><b>refs/heads/feature/login</b><i/><i/><i/></div></div></div>;
 if(step===3)return <div className="tp-scene tp-shared scene-pad"><p>TRAP 02</p><h1>這兩塊，<span>全 repo 共享。</span></h1><div className="tp-shared-map"><div className="tp-top-trees"><Tree name="feature" branch="HEAD · index"/><Tree name="hotfix" branch="HEAD · index"/></div><div className="tp-foundation card"><div><b>REFS</b><span>branches · tags · stash</span></div><div><b>OBJECT DATABASE</b><span>commits · trees · blobs</span></div></div><svg viewBox="0 0 1300 500"><path pathLength="1" d="M230 50 V230 H650 M1070 50 V230 H650 V440"/></svg></div></div>;
 if(step===4)return <div className="tp-scene tp-ripples scene-pad"><p>SHARED ACTIONS</p><h1>一棵動，<span>每棵都看見。</span></h1><div className="tp-action-row">{["delete branch","change tag","fetch","commit"].map((x,i)=><div className="tp-action card" key={x} style={{animationDelay:`${i*130}ms`}}><b>{x}</b><i/></div>)}</div><div className="tp-water"><i/><i/><i/><strong>NOT AN INDEPENDENT CLONE</strong></div></div>;
 if(step===5)return <div className="tp-scene tp-stash scene-pad"><p>TRAP 03</p><h1><span>refs/stash</span> 也只有一疊。</h1><div className="tp-stash-demo"><Tree name="worktree A" branch="stash push 'api'"/><div className="tp-stack">{["stash@{2}","stash@{1}","stash@{0}"].map((x,i)=><div key={x} style={{transform:`translate(${i*22}px,${i*28}px) rotate(${i-1}deg)`}}>{x}</div>)}</div><Tree name="worktree B" branch="stash pop ?"/></div><div className="tp-careful">命名清楚　·　先 list　·　再 pop</div></div>;
 if(step===6)return <div className="tp-scene tp-test scene-pad"><p>BEFORE TEAM ADOPTION</p><h1>特殊工具鏈，<br/><span>先用真專案實測。</span></h1><div className="tp-lab"><div className="tp-test-subject card"><b>submodule</b><i/><i/></div><div className="tp-test-subject card"><b>build tools</b><i/><i/></div><div className="tp-test-subject card"><b>IDE / plugins</b><i/><i/></div><div className="tp-checklist"><strong>TEAM PROJECT</strong>{["create","build","test","remove"].map(x=><span key={x}><i/>{x}</span>)}</div></div></div>;
 return null;
}
