import type { ChapterStepProps } from "../../registry/types";
import "./CmdCreate.css";

const Terminal=({children,title="terminal"}:{children:React.ReactNode;title?:string})=><div className="cc-terminal card"><div className="cc-terminal-top"><i/><i/><i/><b>{title}</b></div><div className="cc-terminal-body">{children}</div></div>;

export default function CmdCreate({step}:ChapterStepProps){
  if(step===0)return <div className="cc-scene cc-menu scene-pad"><div className="cc-prompt">$</div><h1>真的要記的，<br/><span>就這幾個。</span></h1><div className="cc-command-shelf">{["list","add -b","add","cd / new window"].map((x,i)=><div key={x} style={{animationDelay:`${i*110}ms`}}><b>{String(i+1).padStart(2,"0")}</b><span>{x}</span></div>)}</div></div>;
  if(step===1)return <div className="cc-scene cc-list scene-pad"><div className="cc-copy"><p>01 · LOOK AROUND</p><h1>git worktree <span>list</span></h1><small>查看這個 repo 管理的所有 working trees</small></div><Terminal title="project"><div className="cc-line">$ git worktree list</div>{[["/work/project","a31f9c2","[main]"],["/work/project-hotfix","db81e44","[hotfix/payment-timeout]"],["/work/project-feature","02cf1a7","[feature/account-page]"]].map((r,i)=><div className="cc-output" key={r[0]} style={{animationDelay:`${250+i*140}ms`}}><b>{r[0]}</b><span>{r[1]}</span><em>{r[2]}</em></div>)}</Terminal></div>;
  if(step===2)return <div className="cc-scene cc-newbranch scene-pad"><p>02 · CREATE BRANCH + WORKTREE</p><h1>add <span>-b</span></h1><div className="cc-command">git worktree add -b <b>hotfix/payment-timeout</b> ../project-hotfix <b>main</b></div><div className="cc-branch-demo"><div className="cc-main card"><b>main</b><i/></div><svg viewBox="0 0 900 420"><path pathLength="1" d="M80 210 H420 C520 210 480 80 610 80 H820"/></svg><div className="cc-hotfix card"><b>hotfix/payment-timeout</b><span>../project-hotfix</span><div className="cc-folder"><i/><i/></div></div></div></div>;
  if(step===3)return <div className="cc-scene cc-existing scene-pad"><p>03 · EXISTING BRANCH</p><h1>分支已經存在？<br/><span>直接接上目錄。</span></h1><div className="cc-plug"><div className="cc-branch card"><small>BRANCH</small><b>feature/account-page</b><i/></div><div className="cc-cable"><i/><b>git worktree add</b></div><div className="cc-directory card"><small>DIRECTORY</small><b>../project-feature</b><div><i/><i/><i/></div></div></div></div>;
  if(step===4)return <div className="cc-scene cc-switch scene-pad"><div className="cc-switch-title"><p>04 · MOVE YOURSELF, NOT THE CHECKOUT</p><h1><del>git switch</del><br/><span>換資料夾，或換視窗。</span></h1></div><div className="cc-windows"><div className="cc-editor card"><b>project/</b><small>feature/account-page</small><div className="cc-code"><i/><i/><i/></div></div><div className="cc-route"><strong>cd ../project-hotfix</strong><i>→</i></div><div className="cc-editor card"><b>project-hotfix/</b><small>hotfix/payment-timeout</small><div className="cc-code"><i/><i/><i/></div></div></div></div>;
  return null;
}
