import type { ChapterStepProps } from "../../registry/types";
import "./AgentIsolation.css";

const agentShot=()=>`${import.meta.env.BASE_URL}screenshots/agent/claude-worktree.png`;
const Worktree=({task}:{task:string})=><div className="ai-worktree card"><b>{task}</b><span>linked worktree</span><div><i/><i/><i/></div></div>;

export default function AgentIsolation({step}:ChapterStepProps){
 if(step===0)return <div className="ai-scene ai-rule scene-pad"><div className="ai-one hero-num">1</div><h1>個 task<br/><span>一棵 worktree。</span></h1><div className="ai-task-map">{["TASK A","TASK B","TASK C"].map((x,i)=><div key={x} style={{animationDelay:`${i*130}ms`}}><b>{x}</b><i>→</i><span>worktree</span></div>)}</div></div>;
 if(step===1)return <div className="ai-scene ai-layers scene-pad"><p>ISOLATE UP TOP · SHARE DOWN BELOW</p><h1>現場各自隔離，<span>歷史仍是同一份。</span></h1><div className="ai-layer-demo"><div className="ai-worktree-row">{["task-a/","task-b/","task-c/"].map(x=><Worktree task={x} key={x}/>)}</div><div className="ai-shared-history card"><b>SHARED GIT HISTORY</b><div className="ai-commits"><i/><i/><i/><i/><i/></div><span>objects · refs</span></div><svg viewBox="0 0 1500 520"><path pathLength="1" d="M230 70 V220 H750 M750 70 V420 M1270 70 V220 H750"/></svg></div></div>;
 if(step===2)return <div className="ai-scene ai-review scene-pad"><p>CONVERGE WITH EVIDENCE</p><h1>每個 task，<span>逐關檢查。</span></h1><div className="ai-review-flow">{[["DIFF","what changed"],["COMMIT","preserve result"],["MERGE","integrate safely"]].map(([a,b],i)=><div className="ai-review-node" key={a}><article className="card" style={{animationDelay:`${i*140}ms`}}><b>{a}</b><span>{b}</span><i/></article>{i<2&&<strong>→</strong>}</div>)}</div><div className="ai-result-branch"><i/><i/><i/><b>main</b></div></div>;
 if(step===3)return <div className="ai-scene ai-discard scene-pad"><p>FAILURE IS CHEAP TO RECOVER</p><h1>任務不要了，<span>移掉那棵就好。</span></h1><div className="ai-discard-demo"><div className="ai-main-safe card"><b>main worktree</b><span>clean · untouched</span><div><i/><i/><i/></div></div><div className="ai-cut-line"><i/><strong>REMOVE</strong></div><Worktree task="failed-task/"/></div><div className="ai-safe-note">主工作目錄完全不用救</div></div>;
 if(step===4)return <div className="ai-scene ai-claude scene-pad"><div className="ai-claude-copy"><p>CLAUDE CODE</p><h1>建立 task 時，<br/><span>直接勾 worktree。</span></h1><div className="ai-checkbox"><i/> worktree</div><small>專案與 main 分支仍在同一列</small></div><div className="ai-shot card"><img src={agentShot()} alt="Claude Code 建立任務時顯示 worktree 選項"/></div><div className="ai-shot-focus"/></div>;
 if(step===5)return <div className="ai-scene ai-boundary scene-pad"><p>ISOLATION BOUNDARY</p><h1>只隔離<span>工作目錄</span></h1><div className="ai-boundary-demo"><div className="ai-inside"><b>ISOLATED</b>{["files","HEAD","index","checkout"].map(x=><span key={x}>{x}</span>)}</div><div className="ai-wall"><i/><i/><i/><strong>WORKTREE WALL</strong></div><div className="ai-outside"><b>NOT ISOLATED</b>{["database","port","containers","cache"].map(x=><span key={x}>{x}</span>)}</div></div></div>;
 if(step===6)return <div className="ai-scene ai-resources scene-pad"><p>NAME EXTERNAL RESOURCES PER TASK</p><h1>還是共用？<span>就另外命名。</span></h1><div className="ai-resource-grid">{[["DATABASE","app_task_a"],["PORT","4101"],["DOCKER","api-task-a"],["CACHE","cache/task-a"]].map(([a,b],i)=><article className="card" key={a} style={{animationDelay:`${i*120}ms`}}><b>{a}</b><span>{b}</span><div className="ai-name-line"><i/><strong>task-a</strong></div></article>)}</div><div className="ai-resource-rule">worktree 隔離檔案　·　命名策略隔離外部資源</div></div>;
 return null;
}
